import React,{useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {NativeStackNavigationProp} from '@react-navigation/native-stack';
import {useNavigation} from '@react-navigation/native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useAppDispatch,useAppSelector} from '../app/hooks';
import {createGoal} from '../features/progress/progressSlice';
import {selectGoals} from '../features/progress/selectors';
import {ProgressBar} from '../components/ProgressBar';
import {colors} from '../theme/colors';import {spacing} from '../theme/spacing';import {RootStackParamList} from '../types/navigation';
export function GoalsScreen(){const navigation=useNavigation<NativeStackNavigationProp<RootStackParamList>>();const dispatch=useAppDispatch();const goals=useAppSelector(selectGoals);const [title,setTitle]=useState('');const [target,setTarget]=useState('100');const add=async()=>{if(!title.trim())return;await dispatch(createGoal({title,targetValue:Number(target)||100,unit:'%'})).unwrap();setTitle('');};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.header}><Pressable onPress={()=>navigation.goBack()}><Text style={s.back}>‹ Life</Text></Pressable><Text style={s.title}>Goals</Text><Text style={s.subtitle}>Outcomes worth moving toward.</Text></View><View style={s.create}><TextInput value={title} onChangeText={setTitle} placeholder="New goal" placeholderTextColor={colors.textMuted} style={s.input}/><TextInput value={target} onChangeText={setTarget} keyboardType="number-pad" style={[s.input,s.target]}/><Pressable onPress={()=>void add()} style={s.add}><Text style={s.addText}>＋</Text></Pressable></View>{goals.map(g=>{const progress=Math.min(1,g.currentValue/g.targetValue);return <Pressable key={g.id} onPress={()=>navigation.navigate('GoalDetail',{goalId:g.id})} style={s.card}><View style={s.row}><View style={{flex:1}}><Text style={s.cardTitle}>{g.title}</Text><Text style={s.meta}>{g.area.toUpperCase()} · {g.status}</Text></View><Text style={s.value}>{g.currentValue}/{g.targetValue} {g.unit}</Text></View><ProgressBar value={progress}/></Pressable>})}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,paddingBottom:100,gap:spacing.md},header:{gap:3},back:{color:colors.accent,fontWeight:'800'},title:{color:colors.text,fontSize:30,fontWeight:'900'},subtitle:{color:colors.textMuted},create:{flexDirection:'row',gap:8},input:{flex:1,minHeight:48,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,color:colors.text,paddingHorizontal:14,fontSize:16},target:{maxWidth:72},add:{width:48,borderRadius:14,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center'},addText:{color:colors.white,fontSize:24,fontWeight:'900'},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:20,padding:spacing.md,gap:12},row:{flexDirection:'row',justifyContent:'space-between',gap:12},cardTitle:{color:colors.text,fontSize:17,fontWeight:'800'},meta:{color:colors.textMuted,fontSize:11,marginTop:5},value:{color:colors.accent,fontWeight:'800'}});
