import React from 'react';
import {Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {useNavigation,useRoute} from '@react-navigation/native';
import type {NativeStackNavigationProp,NativeStackScreenProps} from '@react-navigation/native-stack';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useAppDispatch,useAppSelector} from '../app/hooks';
import {importStudyMaterial,startStudySession} from '../features/study/studySlice';
import {pickStudyDocument} from '../services/studyDocumentService';
import {colors} from '../theme/colors'; import {spacing} from '../theme/spacing'; import type {RootStackParamList} from '../types/navigation';

type Props=NativeStackScreenProps<RootStackParamList,'StudySubject'>;
const kindIcon=(kind:string)=>kind==='note'?'📝':kind==='pdf'?'📕':kind==='image'?'🖼️':'📄';
export function StudySubjectScreen(){
 const route=useRoute<Props['route']>(); const navigation=useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const dispatch=useAppDispatch();
 const subject=useAppSelector(s=>s.study.subjects.find(x=>x.id===route.params.subjectId)); const materials=useAppSelector(s=>s.study.materials.filter(x=>x.subjectId===route.params.subjectId)); const active=useAppSelector(s=>s.study.sessions.find(x=>x.status==='active'));
 if(!subject)return <SafeAreaView style={styles.safe}><Text style={styles.title}>Subject not found.</Text></SafeAreaView>;
 const importFile=async()=>{try{const file=await pickStudyDocument(subject.id);if(!file)return;await dispatch(importStudyMaterial(file)).unwrap();}catch(e){Alert.alert('Import failed',e instanceof Error?e.message:'Unknown error');}};
 const start=async()=>{try{await dispatch(startStudySession({subjectId:subject.id,materialId:null,goalMinutes:25})).unwrap();navigation.navigate('StudySession');}catch(e){Alert.alert('Could not start session',e instanceof Error?e.message:'Unknown error');}};
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>navigation.goBack()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><View style={{flex:1}}><Text style={styles.eyebrow}>{subject.icon} SUBJECT</Text><Text style={styles.title}>{subject.name}</Text><Text style={styles.muted}>{subject.description}</Text></View></View>
 <View style={styles.actions}><Pressable onPress={()=>navigation.navigate('StudyNoteEditor',{subjectId:subject.id})} style={styles.action}><Text style={styles.actionEmoji}>📝</Text><Text style={styles.actionTitle}>New note</Text></Pressable><Pressable onPress={()=>void importFile()} style={styles.action}><Text style={styles.actionEmoji}>＋</Text><Text style={styles.actionTitle}>Import file</Text></Pressable><Pressable disabled={Boolean(active)} onPress={()=>void start()} style={[styles.action,active&&{opacity:.4}]}><Text style={styles.actionEmoji}>⏱</Text><Text style={styles.actionTitle}>25m focus</Text></Pressable></View>
 <View style={styles.rowBetween}><Text style={styles.section}>Materials</Text><Text style={styles.muted}>{materials.length} items</Text></View>
 {materials.length?materials.map(item=><Pressable key={item.id} onPress={()=>navigation.navigate('StudyMaterial',{materialId:item.id})} style={styles.material}><View style={styles.kind}><Text style={styles.actionEmoji}>{kindIcon(item.kind)}</Text></View><View style={{flex:1,gap:3}}><Text style={styles.materialTitle}>{item.title}</Text><Text style={styles.muted}>{item.kind.toUpperCase()} · {item.progressPercent}% complete{item.kind!=='note'?` · ${item.textExtractionState==='ready'?'searchable':item.textExtractionState==='needs_ocr'?'needs OCR':'not indexed'}`:''}</Text><View style={styles.bar}><View style={[styles.fill,{width:`${item.progressPercent}%`}]} /></View></View><Text style={styles.arrow}>›</Text></Pressable>):<View style={styles.empty}><Text style={styles.muted}>Create a note or import a PDF, image, DOCX or text file.</Text></View>}
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,paddingBottom:90,gap:spacing.lg},header:{flexDirection:'row',gap:12,alignItems:'flex-start'},back:{width:44,height:44,borderRadius:14,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},backText:{color:colors.text,fontSize:30,lineHeight:32},eyebrow:{color:colors.study,fontSize:10,fontWeight:'900',letterSpacing:1},title:{color:colors.text,fontSize:26,fontWeight:'900',marginTop:3},muted:{color:colors.textMuted,fontSize:12,lineHeight:18},actions:{flexDirection:'row',gap:8},action:{flex:1,minHeight:84,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:16,padding:10,justifyContent:'space-between'},actionEmoji:{fontSize:20},actionTitle:{color:colors.text,fontSize:11,fontWeight:'900'},rowBetween:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},section:{color:colors.text,fontSize:18,fontWeight:'900'},material:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:18,padding:14,flexDirection:'row',alignItems:'center',gap:12},kind:{width:44,height:44,borderRadius:13,backgroundColor:colors.studySoft,alignItems:'center',justifyContent:'center'},materialTitle:{color:colors.text,fontWeight:'900',fontSize:15},bar:{height:4,backgroundColor:colors.border,borderRadius:4,overflow:'hidden'},fill:{height:'100%',backgroundColor:colors.study},arrow:{color:colors.study,fontSize:26},empty:{padding:20,borderWidth:1,borderStyle:'dashed',borderColor:colors.border,borderRadius:16}});
