import React,{useState} from 'react';
import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput} from 'react-native';
import {useNavigation,useRoute} from '@react-navigation/native';
import type {NativeStackNavigationProp,NativeStackScreenProps} from '@react-navigation/native-stack';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useAppDispatch} from '../app/hooks'; import {createStudyNote} from '../features/study/studySlice'; import {colors} from '../theme/colors'; import {spacing} from '../theme/spacing'; import type {RootStackParamList} from '../types/navigation';
type Props=NativeStackScreenProps<RootStackParamList,'StudyNoteEditor'>;
export function StudyNoteEditorScreen(){const route=useRoute<Props['route']>();const navigation=useNavigation<NativeStackNavigationProp<RootStackParamList>>();const dispatch=useAppDispatch();const[title,setTitle]=useState('');const[body,setBody]=useState('');const save=async()=>{try{await dispatch(createStudyNote({subjectId:route.params.subjectId,title,bodyText:body})).unwrap();navigation.goBack();}catch(e){Alert.alert('Could not save note',e instanceof Error?e.message:'Unknown error');}};return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable onPress={()=>navigation.goBack()}><Text style={styles.link}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>OFFLINE NOTE</Text><Text style={styles.title}>Capture knowledge</Text><TextInput value={title} onChangeText={setTitle} placeholder="Note title" placeholderTextColor={colors.textMuted} style={styles.input}/><TextInput value={body} onChangeText={setBody} placeholder="Write concepts, explanations, examples…" placeholderTextColor={colors.textMuted} multiline textAlignVertical="top" style={[styles.input,styles.body]}/><Text style={styles.muted}>LifeOS will locally split this note into knowledge chunks so it can be embedded for offline semantic search in a later AI milestone.</Text><Pressable onPress={()=>void save()} style={styles.save}><Text style={styles.saveText}>Save note</Text></Pressable></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,gap:spacing.md,paddingBottom:80},link:{color:colors.study,fontWeight:'800'},eyebrow:{color:colors.study,fontSize:10,fontWeight:'900',letterSpacing:1},title:{color:colors.text,fontSize:28,fontWeight:'900'},input:{minHeight:50,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,borderRadius:14,padding:14,color:colors.text,fontSize:16},body:{minHeight:280},muted:{color:colors.textMuted,fontSize:12,lineHeight:18},save:{minHeight:52,backgroundColor:colors.study,borderRadius:15,alignItems:'center',justifyContent:'center'},saveText:{color:colors.white,fontWeight:'900'}});
