import React,{useState} from 'react';
import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import type {NativeStackNavigationProp} from '@react-navigation/native-stack';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useAppDispatch,useAppSelector} from '../app/hooks';
import {createStudySubject} from '../features/study/studySlice';
import {selectActiveStudySession,selectStudySummary} from '../features/study/selectors';
import {colors} from '../theme/colors';
import {spacing} from '../theme/spacing';
import type {RootStackParamList} from '../types/navigation';

export function StudyScreen(){
  const navigation=useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const dispatch=useAppDispatch();
  const {subjects,materials}=useAppSelector(s=>s.study); const summary=useAppSelector(selectStudySummary); const active=useAppSelector(selectActiveStudySession);
  const [adding,setAdding]=useState(false); const [name,setName]=useState('');
  const add=async()=>{try{await dispatch(createStudySubject({name})).unwrap();setName('');setAdding(false);}catch(e){Alert.alert('Could not create subject',e instanceof Error?e.message:'Unknown error');}};
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.header}><View><Text style={styles.eyebrow}>📚 STUDY MODE</Text><Text style={styles.title}>Knowledge workspace</Text><Text style={styles.muted}>Learn, review and retain — offline.</Text></View><Pressable onPress={()=>navigation.goBack()} style={styles.exit}><Text style={styles.exitText}>Exit</Text></Pressable></View>
    {active?<Pressable style={styles.active} onPress={()=>navigation.navigate('StudySession')}><View><Text style={styles.activeLabel}>ACTIVE STUDY SESSION</Text><Text style={styles.activeTitle}>{subjects.find(x=>x.id===active.subjectId)?.name??'Study'}</Text><Text style={styles.muted}>Goal · {active.goalMinutes} min</Text></View><Text style={styles.arrow}>›</Text></Pressable>:null}
    <View style={styles.stats}><View style={styles.stat}><Text style={styles.statLabel}>This week</Text><Text style={styles.statValue}>{summary.weekMinutes}</Text><Text style={styles.statLabel}>minutes</Text></View><View style={styles.stat}><Text style={styles.statLabel}>Materials</Text><Text style={styles.statValue}>{summary.materials}</Text><Text style={styles.statLabel}>{summary.completedMaterials} completed</Text></View><Pressable onPress={()=>navigation.navigate('Flashcards')} style={styles.stat}><Text style={styles.statLabel}>Due cards</Text><Text style={[styles.statValue,{color:colors.study}]}>{summary.dueCards}</Text><Text style={styles.statLabel}>review now</Text></Pressable></View>
    <View style={styles.rowBetween}><Text style={styles.section}>Subjects</Text><Pressable onPress={()=>setAdding(v=>!v)}><Text style={styles.link}>{adding?'Cancel':'+ New subject'}</Text></Pressable></View>
    {adding?<View style={styles.create}><TextInput value={name} onChangeText={setName} placeholder="e.g. Mobile System Design" placeholderTextColor={colors.textMuted} style={styles.input}/><Pressable onPress={()=>void add()} style={styles.primary}><Text style={styles.primaryText}>Create</Text></Pressable></View>:null}
    <View style={styles.list}>{subjects.map(subject=>{const ms=materials.filter(m=>m.subjectId===subject.id);const avg=ms.length?Math.round(ms.reduce((a,b)=>a+b.progressPercent,0)/ms.length):0;return <Pressable key={subject.id} onPress={()=>navigation.navigate('StudySubject',{subjectId:subject.id})} style={styles.card}><View style={styles.icon}><Text style={styles.iconText}>{subject.icon}</Text></View><View style={styles.cardBody}><Text style={styles.cardTitle}>{subject.name}</Text><Text style={styles.muted}>{subject.description}</Text><View style={styles.bar}><View style={[styles.barFill,{width:`${avg}%`}]} /></View><Text style={styles.meta}>{ms.length} materials · {avg}% progress</Text></View><Text style={styles.arrow}>›</Text></Pressable>})}</View>
    <View style={styles.quickRow}><Pressable onPress={()=>navigation.navigate('Flashcards')} style={styles.quick}><Text style={styles.quickEmoji}>🧠</Text><Text style={styles.quickTitle}>Flashcards</Text><Text style={styles.muted}>Spaced review queue</Text></Pressable><View style={styles.quick}><Text style={styles.quickEmoji}>◉</Text><Text style={styles.quickTitle}>AI-ready knowledge</Text><Text style={styles.muted}>Local chunks prepared for embeddings</Text></View></View>
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.md,paddingBottom:100,gap:spacing.lg},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:12},eyebrow:{color:colors.study,fontSize:11,fontWeight:'900',letterSpacing:1.1},title:{color:colors.text,fontSize:28,fontWeight:'900',marginTop:4},muted:{color:colors.textMuted,fontSize:12,lineHeight:18},exit:{minHeight:44,paddingHorizontal:14,borderWidth:1,borderColor:colors.border,borderRadius:12,justifyContent:'center'},exitText:{color:colors.text,fontWeight:'800'},active:{backgroundColor:colors.studySoft,borderWidth:1,borderColor:colors.study,borderRadius:20,padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},activeLabel:{color:colors.study,fontSize:10,fontWeight:'900',letterSpacing:1},activeTitle:{color:colors.text,fontSize:20,fontWeight:'900',marginTop:4},stats:{flexDirection:'row',gap:8},stat:{flex:1,minHeight:90,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:16,padding:12,justifyContent:'space-between'},statLabel:{color:colors.textMuted,fontSize:10},statValue:{color:colors.text,fontSize:22,fontWeight:'900'},rowBetween:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},section:{color:colors.text,fontSize:18,fontWeight:'900'},link:{color:colors.study,fontWeight:'800'},create:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:16,padding:12,gap:10},input:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:12,paddingHorizontal:12,color:colors.text,fontSize:16},primary:{minHeight:46,backgroundColor:colors.study,borderRadius:12,alignItems:'center',justifyContent:'center'},primaryText:{color:colors.white,fontWeight:'900'},list:{gap:10},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:18,padding:14,flexDirection:'row',alignItems:'center',gap:12},icon:{width:48,height:48,borderRadius:15,backgroundColor:colors.studySoft,alignItems:'center',justifyContent:'center'},iconText:{fontSize:20,color:colors.text,fontWeight:'900'},cardBody:{flex:1,gap:3},cardTitle:{color:colors.text,fontSize:16,fontWeight:'900'},meta:{color:colors.study,fontSize:10,fontWeight:'800'},bar:{height:4,borderRadius:4,backgroundColor:colors.border,overflow:'hidden',marginTop:4},barFill:{height:'100%',backgroundColor:colors.study},arrow:{color:colors.study,fontSize:28},quickRow:{flexDirection:'row',gap:10},quick:{flex:1,minHeight:120,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:18,padding:14,gap:6},quickEmoji:{fontSize:22},quickTitle:{color:colors.text,fontWeight:'900'}});
